// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:823330898154:web:ebf81058f402262e299793',
    messagingSenderId: '823330898154',
    projectId: 'coinhub-451504',
    authDomain: 'coinhub-451504.firebaseapp.com',
    storageBucket: 'coinhub-451504.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:823330898154:android:1d3c3d0f180e32b2299793',
    messagingSenderId: '823330898154',
    projectId: 'coinhub-451504',
    storageBucket: 'coinhub-451504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:823330898154:ios:ade9c6526599b39c299793',
    messagingSenderId: '823330898154',
    projectId: 'coinhub-451504',
    storageBucket: 'coinhub-451504.firebasestorage.app',
    androidClientId:
        '823330898154-vbdagjf2fhf6184m4difqi8gtsqtsb1q.apps.googleusercontent.com',
    iosClientId:
        '823330898154-27ajrbc06rkkl0bscah9h67id4osktb3.apps.googleusercontent.com',
    iosBundleId: 'com.coinhub.coinhub',
  );
}
